version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: asset-management-db
    environment:
      POSTGRES_DB: asset_management
      POSTGRES_USER: asset_user
      POSTGRES_PASSWORD: asset_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asset_user -d asset_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: asset-management-app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://asset_user:asset_password@postgres:5432/asset_management
      JWT_SECRET: your-secret-key-change-this-in-production
      NODE_ENV: production
      CLIENT_URL: http://localhost:5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: