services:
  - type: web
    name: asset-management
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: asset-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false

databases:
  - name: asset-management-db
    databaseName: asset_management
    user: asset_user